services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: po-lokal
    restart: always
    ports:
      - "3006:3006"
    env_file:
      - .env
    environment:
      - PORT=3006
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - po-lokal-network

networks:
  po-lokal-network:
    driver: bridge
