services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: po-lokal
    restart: always
    ports:
      - "3006:3006"
    env_file:
      - .env
    environment:
      - PORT=3006
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - MAYAR_API_KEY=${MAYAR_API_KEY}
      - MAYAR_BASE_URL=${MAYAR_BASE_URL}
    networks:
      - po-lokal-network

networks:
  po-lokal-network:
    driver: bridge
