services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: po-lokal
    restart: always
    network_mode: "host"
    env_file:
      - .env
    environment:
      - PORT=3006
